### ISSUE TITLE
Throttling issues for facebook avatars

### ISSUE THREAD

**Issue by jluisestrada** [Kikobeats/unavatar#119]
Is there any restriction get retrieving the facebook avatars?

Out of 30 request, we get 20 times the facebook logo.

Is it might be the case that facebook is requesting for login?

Any theories?

**Comment by Kikobeats** [comment]
no idea about that – I guess they are rate limit get the avatar in some way

**Comment by Kikobeats** [comment]
I need some feedback to know if this is still happening.

@jluisestrada did you get something like that these days?
