### ISSUE TITLE
Is there any way to get the avatar back on avatars.io?

### ISSUE THREAD

**Issue by luojunyuan** [Kikobeats/unavatar#132]
I found this project via this [blog](https://shkspr.mobi/blog/2020/07/goodbye-avatars-io-hello-unavatar/), there is a project that used avatars.io (aka getchute) for avatar service in 2013-2015 years, now I have many hash values of the avatar.io (the url like avatars.io/13APvgixgc/?size=large) but I can't retrieve the previous avatar

**Comment by Kikobeats** [comment]
I'm sorry for your collection of broken URLs, but unfortunately avatar.io and unavatar are different things :(
