### ISSUE TITLE
Some domain avatars no longer rendering

### ISSUE THREAD

**Issue by pdugan20** [Kikobeats/unavatar#148]
I'm seeing avatars queried by domain no longer render where they previously were working fine.

Examples being:
https://unavatar.now.sh/qz.com
https://unavatar.now.sh/mail.bloombergbusiness.com

...where they return a 504 or just a generic image.

**Comment by Kikobeats** [comment]
Hello, and thanks for reporting!

The issue was happening because of an extra validation to be sure the logo detected over the site has a square resolution.

After implemented that validation at https://github.com/microlinkhq/metascraper/pull/430, I tested your links, and now they working as expected.

If you are only interested into resolve domains, adding the prefix `/microlink` will skip to get avatar from social network, speeding up the response time.

https://unavatar.now.sh/qz.com

**Comment by pdugan20** [comment]
Thanks so much for the quick resolution!

**Comment by pdugan20** [comment]
Hmm the Bloomberg link is still showing as a generic smiley face. Maybe a caching issue on my end?

**Comment by Kikobeats** [comment]
```
curl mail.bloombergbusiness.com
curl: (6) Could not resolve host: mail.bloombergbusiness.com
```

maybe you want to query to `bloombergbusiness.com` instead?

**Comment by pdugan20** [comment]
Hello! It looks like this issue is happening again?

Examples:
https://unavatar.io/qz.com
https://unavatar.io/politico.com

Any ideas? I believe these were all working at one point.

**Comment by Kikobeats** [comment]
That's strange, let me take a look

**Comment by Kikobeats** [comment]
Found the bug, working in a fix

**Comment by pdugan20** [comment]
Really appreciate it!

**Comment by Kikobeats** [comment]
Working back!

![CleanShot 2021-07-18 at 00 54 16@2x](https://user-images.githubusercontent.com/2096101/126051016-1e14aa86-15a3-469f-a3c4-1f5d03458371.png)

For any reason, `https://unavatar.io/politico.com` is returning HTML content:

```
curl https://unavatar.io/politico.com
<figure class="art ">
    <div class="fig-graphic">
        <img src="https://static.politico.com/dims4/default/24d02f9/2147483647/resize/1160x%3E/quality/90/?url=https%3A%2F%2Fstatic.politico.com%2Fb8%2Fb0%2F16745e704246beaaafc23cb38f86%2Fapple-touch-icon-144x144-precomposed.png" alt="politico favicon" title="politico favicon"></div>
    </figure>
```

The URL detected returning the HTML content is `https://www.politico.com/android-chrome-192x192.png`:

```
curl https://www.politico.com/android-chrome-192x192.png
<figure class="art ">
    <div class="fig-graphic">
        <img src="https://static.politico.com/dims4/default/24d02f9/2147483647/resize/1160x%3E/quality/90/?url=https%3A%2F%2Fstatic.politico.com%2Fb8%2Fb0%2F16745e704246beaaafc23cb38f86%2Fapple-touch-icon-144x144-precomposed.png" alt="politico favicon" title="politico favicon"></div>
    </figure>
```

Unfortunately, I can't do too much there :(

**Comment by Kikobeats** [comment]
Working back!

![CleanShot 2021-07-18 at 00 54 16@2x](https://user-images.githubusercontent.com/2096101/126051016-1e14aa86-15a3-469f-a3c4-1f5d03458371.png)

I noted `https://unavatar.io/politico.com` is returning HTML content in an arbitrary way:

```
curl https://unavatar.io/politico.com
<figure class="art ">
    <div class="fig-graphic">
        <img src="https://static.politico.com/dims4/default/24d02f9/2147483647/resize/1160x%3E/quality/90/?url=https%3A%2F%2Fstatic.politico.com%2Fb8%2Fb0%2F16745e704246beaaafc23cb38f86%2Fapple-touch-icon-144x144-precomposed.png" alt="politico favicon" title="politico favicon"></div>
    </figure>
```

The URL detected returning the HTML content is `https://www.politico.com/android-chrome-192x192.png`:

```
curl https://www.politico.com/android-chrome-192x192.png
<figure class="art ">
    <div class="fig-graphic">
        <img src="https://static.politico.com/dims4/default/24d02f9/2147483647/resize/1160x%3E/quality/90/?url=https%3A%2F%2Fstatic.politico.com%2Fb8%2Fb0%2F16745e704246beaaafc23cb38f86%2Fapple-touch-icon-144x144-precomposed.png" alt="politico favicon" title="politico favicon"></div>
    </figure>
```

Unfortunately, I can't do too much there :(

**Comment by pdugan20** [comment]
Thanks for being on top of this!

**Comment by pdugan20** [comment]
Hate to keep bothering you but it looks like this is broken again? qz.com which was working with your example about now doesn't return an image:
https://unavatar.io/qz.com

**Comment by Kikobeats** [comment]
hum we need to find a better way to debug this kind of issue.

The link si working fine to some. What are you experience? Can you attach a screenshot and an HTTP status report?

**Comment by pdugan20** [comment]
I get the following:
```
curl https://unavatar.now.sh/qz.com
Redirecting to https://unavatar.vercel.app/qz.com (308)
```
...and the redirect just the generic mac smiley face. This url was working in the example you shared about two days ago.

**Comment by Kikobeats** [comment]
why not you just query against `https://unavatar.io` domain?

<img width="453" alt="CleanShot 2021-07-19 at 16 50 29@2x" src="https://user-images.githubusercontent.com/2096101/126179820-0ab5c379-3d2e-4991-865d-75a6e167c987.png">

**Comment by pdugan20** [comment]
Going directly to the URL also gives me the same placeholder
<img width="1434" alt="Screen Shot 2021-07-19 at 7 53 50 AM" src="https://user-images.githubusercontent.com/1837100/126180491-806afb69-44c0-42ac-a493-3dab62f86e5b.png">

**Comment by Kikobeats** [comment]
Can you perform the following command and paste the output?

```
curl -I -s -X GET https://unavatar.io/qz.com
```

**Comment by pdugan20** [comment]
Yup!
```
curl -I -s -X GET https://unavatar.io/qz.com
HTTP/2 200 
date: Mon, 19 Jul 2021 16:07:26 GMT
content-type: image/png
content-length: 3483
content-disposition: inline; filename=image.png
x-permitted-cross-domain-policies: none
access-control-allow-origin: *
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=YaKUNIhSbLRt7jNhKo6U7kmwi9CczLaqJqG%2BZ1XTQPjJkYiYYjytR0y6N3R6Vkbl2vUMCZ6I2KJ7r%2FI3YdtU1e%2B2vyJKAKst1PuJEy8UYw16u4LWyolYJcHjPrK8uOw6K3Ha"}],"group":"cf-nel","max_age":604800}
referrer-policy: no-referrer
x-cache-status: MISS
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
etag: "85-v2k3h23t0BTnk590Mk9xGUaH4rU"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
cache-control: public, max-age=31536000
x-images-api: 5
x-download-options: noopen
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-xss-protection: 0
vary: Accept-Encoding
expires: Sat, 16 Jul 2022 14:05:49 GMT
x-frame-options: SAMEORIGIN
content-security-policy: default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
x-content-type-options: nosniff
nel: {"report_to":"cf-nel","max_age":604800}
x-cache-expired-at: 1d
age: 177738
x-dns-prefetch-control: off
cf-bgj: h2pri,csam-hash
x-vercel-cache: MISS
x-vercel-id: pdx1::sfo1::8jk8m-1626533099927-55f6272a28f0
cf-cache-status: HIT
accept-ranges: bytes
server: cloudflare
cf-ray: 671533e70ebb08db-SEA
```
