### ISSUE TITLE
support multiple usernames / emails

### ISSUE THREAD

**Issue by ahmadnassri** [Kikobeats/unavatar#20]
## Why

- I have usernames (or a *guess* of usernames) from multiple sources github, twitter, etc ... I want to pass them all to `unavatar` because I may not know which are real
- I have multiple emails for a user, unavatar may find some matches for some but not others

## How

use comma separated list of names to find first match

```
<img src="https://unavatar.now.sh/:username1,:username2,:username3,email1,email2" />
```

**Comment by ahmadnassri** [comment]
this could also apply to emails!

**Comment by Kikobeats** [comment]
I added at `v1.2.0` the ability to disable fallback avatar.

Now have the right avatar from a list of usernames or emails is so easy 🙂

```
'use strict'

const got = require('got')
const pAny = require('p-any')

const unavatar = async username =>
  got(`http://localhost:3000/twitter/${username}?json&fallback=false`, {
    json: true
  }).then(res => res.body)

const usernames = ['oadsopadk', 'oaksdpoksadpokaopd', 'kikobeats']
const promises = usernames.map(username => unavatar(username))
pAny(promises).then(json => console.log('done', json.url))
```

**Comment by ahmadnassri** [comment]
nice 👏
