### ISSUE TITLE
some request cause unexpected behavior

### ISSUE THREAD

**Issue by jahirfiquitiva** [Kikobeats/unavatar#99]
I'm currently getting this error :/

![Shot 2020-06-27 at 22 00 24](https://user-images.githubusercontent.com/10360816/85936556-a5ea0e00-b8c1-11ea-8d76-51e8fac8f1f5.png)

**Comment by Kikobeats** [comment]
It works fine to me

<img width="1406" alt="Screenshot 2020-06-28 at 11 03 25" src="https://user-images.githubusercontent.com/2096101/85943227-04010a80-b92f-11ea-8dfa-a2a5dfde191f.png">

Looks like it could be an AWS Lambda/Vercel failover

Can you confirm now works for you?

**Comment by jahirfiquitiva** [comment]
I'm using unavatar to show some photos in [this site](https://jahir.dev/donate) butt none of them are loading 😕

**Comment by Kikobeats** [comment]
Hum, it looks a problem related with HTTP underline
https://github.com/sindresorhus/got/issues/1308

**Comment by Kikobeats** [comment]
Should be fixed at https://github.com/Kikobeats/unavatar/pull/100
